### ISSUE TITLE
Back up and delete `com.apple.windowserver*` plist files in other directories

### ISSUE THREAD

**Issue by jamescmartinez** [sudowork/fix_m1_rgb#1]
From my comment [here](https://gist.github.com/adaugherity/7435890#gistcomment-3767672), this script did not work for me until I manually deleted the display plist in ` ~/Library/Preferences/ByHost`.

Is this something that you feel should be added to the script?

**Comment by sudowork** [comment]
Thanks for the report. Done in 413ff4887fd2eee49e08cebdf6922d56b4783327. Or at least, I am backing up and making the same modifications to that file. I opted not to delete it since there may be other preferences that are desirable to keep. Also, I am only looking for the file specific to the host (computer) that the script is being run from to be conservative.

Would you be able to help me verify that the file path is: `~/Library/Preferences/ByHost/com.apple.windowserver.displays.<UUID>.plist`?

**Comment by jamescmartinez** [comment]
Yup, that's the one. Thanks @sudowork!
